### ISSUE TITLE
Bicycle touring community roadmap

### ISSUE THREAD

**Issue by mariha** [OpenHospitalityNetwork/fedi-trustroots#29]
_A meta issue describing high level roadmap for the bicycle touring community_

- tell WarmShowers story from our perspective (contributors to the community built WS Android App)
  - [x] message from devs [in WS Android App](https://github.com/warmshowers/wsandroid/issues/360) and in https://warmshowers.bike
  - [x] [WarmShowers Uncensored](https://gitlab.com/-/snippets/2111860)
  - [ ] update [WS history in Wikipedia](https://en.wikipedia.org/wiki/Warm_Showers#History)
- make it easy to move from WarmShowers to Trustroots
  - [ ] https://github.com/Trustroots/trustroots/issues/2200
  - [ ] blog post about similarities and differences between the platforms and communities
- spread the knowledge about Trustroots in bicycle touring community, grow cycling circle and instigate core volunteers team
  - [x] https://github.com/warmshowers/wsandroid/issues/360
  - [ ] https://github.com/Trustroots/trustroots/issues/2199
  - incubate self-organized volunteers team within Trustroots team
    - [ ] [Open Alternative to WarmShowers.org](https://www.facebook.com/groups/243374777243989) FB group
    - [ ] sent email to everyone from [the survey](https://warmshowers.bike/survay) 
- spin up an instance of TR software for bicycle touring community
  - [x] deploy it - https://demo.openhospitality.network
  - [ ] whitelabel it
  - [ ] rebrand: new name, logo and descriptions
  - [ ] adapt (hide circles, meetup, friends, messaging? ...)
- show on a map hosts from the other platform, no data is shared
  - [ ] map with anonymous hosts, individual or aggregated: https://github.com/OpenHospitalityNetwork/openHospitality.network/issues/26
  - [ ] ? sso to request a stay https://github.com/OpenHospitalityNetwork/openHospitality.network/issues/6
- (?) communication across platforms - https://github.com/OpenHospitalityNetwork/openHospitality.network/issues/30
  - [ ] use existing communication channels: phone (sms), internet communicators that people may already use
  - [ ] messaging: embed, integrate or implement interoperable messaging 
- (?) make it easy to move from one to the other platform - https://github.com/OpenHospitalityNetwork/openHospitality.network/issues/5
  - [ ] import/export
  - [ ] ...
- broadcast info about the new platform

Continue with [Fediverse roadmap](https://github.com/OpenHospitalityNetwork/openHospitality.network/issues/33), feedback from the [survey for WS Android App users](https://github.com/warmshowers/wsandroid/issues/361) and community organizing as usual within sibling Trustroots team.
