### ISSUE TITLE
Refugees supporters roadmap

### ISSUE THREAD

**Issue by mariha** [OpenHospitalityNetwork/fedi-trustroots#92]
## Refugees help roadmap

_meta issue_ that organizes other issues useful for a platform for people leaving Ukraine at the moment.

Feel free to _edit_ as you see the need.

### the MVP

Once done, we’ll broadcast  info about https://refugees.openHospitality.network to main refugees helping organizations and have people registered / find a place to stay.

- [ ] A host is able to register with their accommodation - right now: 
   - [ ] Problem: verification emails are not delivered
   - [ ] Problem: verification emails mention Trustroots 

- [x] A refugee is able to search for hosts and message/contact them
   - [x] Filter by languages spoken
   - [x] Filter by circle/ kind of help needed
   - [x] Filter by number of people

- [ ] The platform has a look and feel dedicated to refugees (and their hosts)
   - [x] domain - refugees.openHospitality.network
   - [ ] registration/how-it-works page
   - [ ] other places

At this point we can broadcast info about the platform

### Beyond MVP

- [ ] circles are reused for type of help being offered: accommodation, legal help, translations, …
   - [ ] _(work with NGOs to define best categories)_
   - [ ] define them in the config

- [ ] NGOs are added as Points of Interest on a dedicated layer in OpenStreetMap - accessible for everyone, without logging in, displayed in our app
   - [ ] experiment with what makes sense and how to add points
   - [ ] _request data about organizations_
   - [ ] add that data to OSM _or_
   - [ ] train / document how to add new org to the map
   - [ ] document + possibly help NGOs embed OSM map with that layer on, on their web pages

- [ ] data from the [pad](https://pad.riseup.net/p/E0x-D-ZiJZlHXbDAGG7W-keep)  is moved to the platform
- [ ] data from the [Hospitality Map](https://mapagoscinnosci.pl) is moved to the platform
- [ ] maybe data from Refugees Welcome is moved to the platform (currently hosts are not displayed)

To consider:
- what if many people register?
- devops
- fediverse changes (Lennart & Chagai) - cors etc - move to a branch?
- ?
- domain name

**Comment by mariha** [comment]
a list from Mikael what to do: https://github.com/orgs/Trustroots/projects/6/views/1
